### ISSUE TITLE
KeyError: 'start_actual'

### ISSUE THREAD

**Issue by sushi-chaaaan** [ombe1229/holodex#16] opened 2022-01-18 04:16 UTC
```

> ERROR:asyncio:Task exception was never retrieved
> future: <Task finished name='Task-1' coro=<Loop._loop() done, defined at /app/.heroku/python/lib/python3.10/site-packages/discord/ext/tasks/__init__.py:161> exception=KeyError('start_actual')>

Traceback (most recent call last):
File "/app/.heroku/python/lib/python3.10/site-packages/discord/ext/tasks/__init__.py", line 207, in _loop
raise exc
File "/app/.heroku/python/lib/python3.10/site-packages/discord/ext/tasks/__init__.py", line 178, in _loop
await self.coro(*args, **kwargs)
File "/app/Cog/holodex.py", line 39, in _get_stream
await self.get_stream_method(self.bot.holodex)
File "/app/Cog/holodex.py", line 56, in get_stream_method
await self.confirm_nowgoing_stream(nowgoing_tuple, yt_channel)
File "/app/Cog/holodex.py", line 115, in confirm_nowgoing_stream
actual_start = holodex.time_going(x)
File "/app/Cog/holodex_process.py", line 34, in time_going
actual_start_stamp = x.start_actual.replace(

> File "/app/.heroku/python/lib/python3.10/site-packages/holodex/model/live.py", line 51, in start_actual
> return self._response["start_actual"]
> KeyError: 'start_actual'
> ERROR:asyncio:Unclosed client session
> client_session: <aiohttp.client.ClientSession object at 0x7ff366758be0>
```

Script:https://github.com/sushi-chaaaan/sakamata-alpha-pycord/blob/stream-cog/Cog/holodex.py#L114

This error is often happen since I updated holodex from 0.9.7 to 0.10.7

**Comment by ombe1229** [comment] 2022-01-18 07:09
KeyError is probably caused by that  "start_actual"  value being optional.
https://github.com/sushi-chaaaan/sakamata-alpha-pycord/blob/stream-cog/Cog/holodex_process.py#L33
I think it can be fixed by handling it from here

**Closed** 2022-01-18 07:36 UTC
Labels: bug
